# -*- coding: utf-8 -*-
"""Week12_A105260065_呂欣容.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FNAuUKuq1GEbQkrVm0bxBOtI7jBPehCK

隨堂練習:印出介於 x 到 y 之間的奇數（包含 x 與 y 假如它們是奇數）
"""

x = int(input("請輸入起始的正整數："))
y = int(input("請輸入終止的正整數："))
odds = []
for i in range(x, y + 1):
    mod = i % 2
    if mod == 1:
        odds.append(i)
print(odds)

"""隨堂練習:承接上題，介於 x 到 y 之間的奇數有幾個（包含 x 與 y 假如它們是奇數）"""

print(len(odds)) # 記數

"""隨堂練習:承接上題，介於 x 到 y 之間的奇數加總為何（包含 x 與 y 假如它們是奇數）"""

print(sum(odds)) # 加總

"""隨堂練習:將復仇者聯盟系列電影評等大於 8 分的挑選出來"""

avengers_ratings = [8.1, 7.3, 8.5, 8.8]
recommendations = [i for i in avengers_ratings if i >= 8]
print(recommendations)

"""隨堂練習:標記復仇者聯盟的上映順序

第 1 部上映的復仇者聯盟是：The Avengers

第 2 部上映的復仇者聯盟是：Avengers: Age of Ultron

第 3 部上映的復仇者聯盟是：Avengers: Infinity War

第 4 部上映的復仇者聯盟是：Avengers: Endgame
"""

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for idx, movie in enumerate(avengers):
    print("第{}部上映的復仇者聯盟電影:{}".format(idx+1, movie))

"""隨堂練習:標記復仇者聯盟的上映順序與年份
第 1 部復仇者聯盟：The Avengers 上映年份為 2012

第 2 部復仇者聯盟：Avengers: Age of Ultron 上映年份為 2015

第 3 部復仇者聯盟：Avengers: Infinity War 上映年份為 2018

第 4 部復仇者聯盟：Avengers: Endgame 上映年份為 2019
"""

years = [2012, 2015, 2018, 2019]
for year, movie in zip(years, avengers):
    print("{}上映的年份是{}".format(movie, year))

