# -*- coding: utf-8 -*-
"""Ｗeek11_A105260065_呂欣容.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1noeRXzFnNGFOVOWgbozEQH0wpfZgaRjK

使用tuple
"""

primes = (2, 3, 5, 7, 11)
print(type(primes))

"""常用的 tuple 操作

1.len() 觀察長度

2.索引（Indexing）

3.切割（Slicing）

1.len() 觀察長度
"""

print(len(primes))

"""2.索引（indexing）"""

print(primes[0])
print(primes[1])
print(primes[-1])
print(primes[-2])

"""3.切割（slicing）

start 起始索引（包含）

stop 結束索引（不包含）

step 間距
"""

print(primes[::2])

"""獲取 dict 的標籤與資料

.keys()：取得標籤

.values()：取得資料

.items()：同時取得標籤和資料
"""

the_avengers = {
    "Iron Man": "Tony Stark",
    "Captain America": "Steve Rogers",
    "Hulk": "Bruce Banner",
    "Thor": "Thor",
    "Black Widow": "Natasha Romanoff",
    "Hawkeye": "Clint Barton"
}

print(type(the_avengers))

print(the_avengers.keys()) #取得標籤

print(the_avengers.values()) #取得資料

print(the_avengers.items()) #同時取得標籤和資料

living_area = input("請輸入您的居住縣市:")
living_cost = None
if living_area == '臺北市':
    living_cost = 17005
elif living_area == '新北市':
    living_cost = 15500
elif living_area == '桃園市':
    living_cost = 15281
elif living_area == '臺中市':
    living_cost = 14596
elif living_area == '臺南市':
    living_cost = 12388
elif living_area == '高雄市':
    living_cost = 13099
elif living_area == '非六都之縣市':
    living_cost = 12388
elif living_area == '金門縣連江縣':
    living_cost = 11648

if living_cost is None:
    print("請重新輸入居住縣市")
else:
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))

living_cost_dict = {
    '臺北市': 17005,
    '新北市': 15500,
    '桃園市': 15281,
    '臺中市': 14596,
    '臺南市': 12388,
    '高雄市': 13099,
    '非六都之縣市': 12388,
    '金門縣連江縣': 11648
}
living_area = input("請輸入您的居住縣市:")
try:
    living_cost = living_cost_dict[living_area]
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
except KeyError:
    print("請重新輸入居住縣市")

"""set 能運行集合運算

| 聯集

& 交集

-差異

^ 對稱差異
"""

primes = {2, 3, 5, 7, 11, 13}
odds = {1, 3, 5, 7, 9, 11, 13}
print(type(primes))
print(type(odds))

# 交集
primes & odds

# 聯集
primes | odds

# 差異
print(primes - odds)
print(odds - primes)

# 對稱差異
primes ^ odds

"""使用iter"""

primes

I = iter(primes)
next(I)

"""使用range"""

for i in range(1, 101, 1):
    print(i)

