# -*- coding: utf-8 -*-
"""W9_A105260065_呂欣容.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EoTM5v561ijRvaTspNrzZN28i-DoU4xu

隨堂練習：承接上題，介於 x 到 y 之間的奇數有幾個（包含 x 與 y 假如它們是奇數）
"""

x = int(input("請輸入起始的正整數："))
y = int(input("請輸入終止的正整數："))
odd_counter = 0 # 歸零
i = x # start
while i <= y: # stop
    if i % 2 == 1: 
       odd_counter += 1 # 計數累計
    i += 1 # step
print(odd_counter)

"""隨堂練習：承接上題，介於 x 到 y 之間的奇數加總為何（包含 x 與 y 假如它們是奇數）"""

x = int(input("請輸入起始的正整數："))
y = int(input("請輸入終止的正整數："))
odd_summation = 0 # 歸零
i = x # start
while i <= y: # stop
    if i % 2 == 1: 
       odd_summation = odd_summation + i # 數值累加
    i += 1 # step
print(odd_summation)

"""作業：Fizz-Buzz with while
從 1 印到 100

如果是 3 的倍數印出 "Fizz"

如果是 5 的倍數印出 "Buzz"

如果是 15 的倍數印出 "Fizz Buzz"

其他情況印出該正整數即可
"""

i = 1 
while i <= 100:
    if i % 15 == 0:
        print("Fizz Buzz") 
    elif i % 5 == 0:
        print("Fizz") 
    elif i % 3 == 0:
        print("Buzz")
    else:
        print(i)
    i += 1

