# -*- coding: utf-8 -*-
"""W4_A105260065_呂欣容.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBO4CxVUcq9PPfL0aWQc_empNpYc-HDL

隨堂練習27：將目前的攝氏氣溫轉換為華氏氣溫
Fahrenheit = Celsius × 9/5 + 32
"""

current_celsius = 25
current_fahrenheit = current_celsius * 9 / 5 + 32
print(current_fahrenheit)

"""隨堂練習28：將目前的華氏氣溫轉換為攝氏氣溫
Celsius = (Fahrenheit − 32) × 5/9
"""

current_tempc = (current_trmpf - 32) * 5 / 9
print(current_tempc)

"""隨堂練習29：計算俠客歐尼爾巔峰時期的 BMI 身體質量指數
NBA 史上最偉大的中鋒之一「柴油引擎」俠客歐尼爾（Shaquille O’Neal）巔峰時期的身
高為 216 公分、體重為 147 公斤。
BMI = weightkg/height²m
"""

shaq_weight = 147
shaq_height = 216
shaq_bmi = shaq_weight / (shaq_height/100)**2
print(shaq_bmi)

"""隨堂練習42：What did Ross say?
Let's put aside the fact that you "accidentally" pick up my grandmother's ring.
"""

ross_said = """Let's put aside the fact that you "accidentally" pick up my grandmother's ring"""
print(ross_said)

ross_said = "Let's put aside the fact that you \"accidentally\" pick up my grandmother's ring"
print(ross_said)

ross_said = 'Let\'s put aside the fact that you "accidentally" pick up my grandmother\'s ring'
print(ross_said)

"""隨堂練習50：讓使用者輸入城市名稱與天氣，並印出「我在OOO，天氣OOO」。"""

city = input("請輸入您在的城市名稱")
weather = input("請輸入目前的天氣")

print("我在{}，天氣{}".format(city, weather))

"""隨堂練習68 : 球員 BMI 與過重判斷
以 input() 函數請使用者輸入球員姓名、身高與體重，計算球員的 BMI 並且印出超過 30 代表過重，請印出判斷結果。
"""

player_name = input("請輸入球員姓名:")
player_height = input("請輸入球員身高(cm):")
player_weight = input("請輸入球員體重(kg):")

player_height = int(player_height)
player_weight = int(player_weight)
player_bmi = format(player_weight / (player_height/100)**2)
player_bmi = float(player_bmi)
print(player_bmi)

print("{}的身體質量指數為：{:.2f}".format(player_name, player_bmi))
print("{}是否過重：{}".format(player_name, player_bmi > 30))

