# -*- coding: utf-8 -*-
"""Week3_A105260065_呂欣容_Google colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sivq-P5-TfzCSfwHdc8NrWa6DVmpNGix

隨堂練習：將電影(https://www.imdb.com/title/tt4154796/) 頁面中的三個資訊儲存為物件並且印出來，片長（以分鐘為單位)、評分、片名，並使用 type() 函數將這三個物件的類別印出來
"""

movie_title = "Avengers: Endgame"
movie_length = 181
movie_rating = 8.4

print(movie_title)
print(movie_length)
print(movie_rating)

print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))