# -*- coding: utf-8 -*-
"""W8_A105260065_呂欣容.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BIADnZQL7hWyt3_dFaOmGat-_jmWJmM3

Fizz-Buzz

以 input() 函數請使用者輸入一個正整數

如果是 3 的倍數印出 "Fizz"

如果是 5 的倍數印出 "Buzz"

如果是 15 的倍數印出 "Fizz Buzz"

其他情況印出該正整數即可
"""

user_int = int(input("請輸入一個正整數:"))
if user_int % 15 == 0:
    print("Fizz Buzz")
elif user_int % 5 == 0:
    print("Buzz")
elif user_int % 3 == 0:
    print("Fizz")
else:
    print(user_int)

"""隨堂練習：印出介於 x 到 y 之間的奇數（包含 x 與 y 假如它們是奇數）"""

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數"))
i = x
while i <= y:
    if i % 2 == 1:
        print(i)
    i += 1

